"""
Compare blueprint — Before vs After report comparison engine.
Compares JSON summary files generated by health_check.sh.
Covers: System, Storage, Memory, Services, Network, Security.
"""

import os
import json
import logging
from datetime import datetime

from flask import Blueprint, render_template, request, jsonify, abort, session, redirect, url_for

from app.config import Config

compare_bp = Blueprint("compare", __name__)
logger = logging.getLogger(__name__)


# =============================================================================
# JSON LOADING & REPORT DISCOVERY
# =============================================================================

def resolve_json_filename(filename):
    """Normalize input filename (.html, .txt, or .json) to .json."""
    if not filename:
        return ""
    base = os.path.splitext(filename)[0]
    return base + ".json"


def load_json(filepath):
    """
    Load and return a JSON summary file.
    Returns (data, error_message).
    """
    if not os.path.isfile(filepath):
        return None, f"File not found: {filepath}"

    file_size = os.path.getsize(filepath)
    if file_size == 0:
        return None, f"File is empty (0 bytes): {filepath}"

    try:
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
            if not isinstance(data, dict):
                return None, f"Invalid JSON structure (expected root dictionary): {filepath}"
            return data, None
    except json.JSONDecodeError as e:
        logger.error("JSON decode error in %s: %s", filepath, e)
        return None, f"Invalid JSON syntax at line {e.lineno}, column {e.colno}: {e.msg}"
    except Exception as e:
        logger.error("Failed to load JSON %s: %s", filepath, e)
        return None, f"Unexpected error reading file: {str(e)}"


def get_json_reports(hostname):
    """Get all JSON reports for a hostname sorted newest-first."""
    host_dir = os.path.join(Config.WEB_ROOT, hostname)
    if not os.path.isdir(host_dir):
        return []

    reports = []
    # Collect all .json reports or matching .html reports
    seen = set()
    for f in sorted(os.listdir(host_dir), reverse=True):
        if f.startswith("HealthCheck_") and f != "latest.html":
            json_file = resolve_json_filename(f)
            if json_file in seen:
                continue

            json_path = os.path.join(host_dir, json_file)
            if os.path.isfile(json_path):
                seen.add(json_file)
                mtime = os.path.getmtime(json_path)
                reports.append({
                    "filename": json_file,
                    "mtime": mtime,
                    "mtime_str": datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S"),
                    "size_kb": round(os.path.getsize(json_path) / 1024, 1),
                })

    return reports


# =============================================================================
# COMPARISON ENGINE
# =============================================================================

def eval_filesystem_status(usage_pct):
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 80:
        return "PASS"
    elif pct < 90:
        return "WARNING"
    return "FAIL"


def eval_memory_status(usage_pct):
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 80:
        return "PASS"
    elif pct < 90:
        return "WARNING"
    return "FAIL"


def eval_swap_status(usage_pct):
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 20:
        return "PASS"
    elif pct < 50:
        return "WARNING"
    return "FAIL"


def eval_service_status(old_state, new_state):
    s_new = str(new_state).upper() if new_state else "UNKNOWN"
    s_old = str(old_state).upper() if old_state else "UNKNOWN"

    if s_old == "STOPPED" and s_new in ("RUNNING", "ACTIVE"):
        return "RESTARTED"
    elif s_new in ("RUNNING", "ACTIVE"):
        return "RUNNING"
    elif s_new == "STOPPED":
        return "STOPPED"
    elif s_new == "NOT_INSTALLED":
        return "REMOVED"
    return "CHANGED" if s_old != s_new else "NO_CHANGE"


def compare_system(old, new):
    results = []
    sys_old = old.get("system", {})
    sys_new = new.get("system", {})

    fields = [
        ("Hostname", "hostname"),
        ("FQDN", "fqdn"),
        ("Operating System", "os"),
        ("Kernel Version", "kernel"),
        ("CPU Cores", "cpu_cores"),
        ("Total Memory", "ram_total"),
        ("System Uptime", "uptime"),
    ]

    for label, key in fields:
        old_val = str(sys_old.get(key, "N/A"))
        new_val = str(sys_new.get(key, "N/A"))
        changed = old_val != new_val
        results.append({
            "item": label,
            "previous": old_val,
            "current": new_val,
            "difference": f"{old_val} → {new_val}" if changed else "No Change",
            "status": "CHANGED" if changed else "NO_CHANGE",
            "type": "text",
        })

    return results


def compare_storage(old, new):
    results = []

    fs_old = {item["mount"]: item for item in old.get("storage", {}).get("filesystems", []) if "mount" in item}
    fs_new = {item["mount"]: item for item in new.get("storage", {}).get("filesystems", []) if "mount" in item}

    all_mounts = sorted(set(list(fs_old.keys()) + list(fs_new.keys())))

    for mount in all_mounts:
        old_entry = fs_old.get(mount, {})
        new_entry = fs_new.get(mount, {})

        old_pct = old_entry.get("use_pct", "N/A")
        new_pct = new_entry.get("use_pct", "N/A")

        old_used = f"{old_entry.get('used', 'N/A')} / {old_entry.get('size', 'N/A')} ({old_pct})" if old_entry else "Not Mounted"
        new_used = f"{new_entry.get('used', 'N/A')} / {new_entry.get('size', 'N/A')} ({new_pct})" if new_entry else "Unmounted"

        status = eval_filesystem_status(new_pct) if new_entry else "FAIL"

        try:
            prev_num = float(str(old_pct).replace("%", "")) if old_pct != "N/A" else 0
        except (ValueError, TypeError):
            prev_num = 0

        try:
            curr_num = float(str(new_pct).replace("%", "")) if new_pct != "N/A" else 0
        except (ValueError, TypeError):
            curr_num = 0

        results.append({
            "item": f"Mount {mount}",
            "previous": old_used,
            "current": new_used,
            "status": status,
            "type": "progress",
            "prev_pct": prev_num,
            "curr_pct": curr_num,
        })

    return results


def compare_memory(old, new):
    results = []
    mem_old = old.get("memory", {})
    mem_new = new.get("memory", {})

    # RAM Usage
    ram_old_pct = mem_old.get("ram_used_pct", "N/A")
    ram_new_pct = mem_new.get("ram_used_pct", "N/A")
    ram_old_str = f"{mem_old.get('ram_used', 'N/A')} / {mem_old.get('ram_total', 'N/A')} ({ram_old_pct})"
    ram_new_str = f"{mem_new.get('ram_used', 'N/A')} / {mem_new.get('ram_total', 'N/A')} ({ram_new_pct})"

    try:
        ram_prev_num = float(str(ram_old_pct).replace("%", ""))
    except (ValueError, TypeError):
        ram_prev_num = 0

    try:
        ram_curr_num = float(str(ram_new_pct).replace("%", ""))
    except (ValueError, TypeError):
        ram_curr_num = 0

    results.append({
        "item": "RAM Memory Usage",
        "previous": ram_old_str,
        "current": ram_new_str,
        "status": eval_memory_status(ram_new_pct),
        "type": "progress",
        "prev_pct": ram_prev_num,
        "curr_pct": ram_curr_num,
    })

    # Swap Usage
    swap_old_pct = mem_old.get("swap_used_pct", "N/A")
    swap_new_pct = mem_new.get("swap_used_pct", "N/A")
    swap_old_str = f"{mem_old.get('swap_used', 'N/A')} / {mem_old.get('swap_total', 'N/A')} ({swap_old_pct})"
    swap_new_str = f"{mem_new.get('swap_used', 'N/A')} / {mem_new.get('swap_total', 'N/A')} ({swap_new_pct})"

    try:
        swap_prev_num = float(str(swap_old_pct).replace("%", ""))
    except (ValueError, TypeError):
        swap_prev_num = 0

    try:
        swap_curr_num = float(str(swap_new_pct).replace("%", ""))
    except (ValueError, TypeError):
        swap_curr_num = 0

    results.append({
        "item": "Swap Memory Usage",
        "previous": swap_old_str,
        "current": swap_new_str,
        "status": eval_swap_status(swap_new_pct),
        "type": "progress",
        "prev_pct": swap_prev_num,
        "curr_pct": swap_curr_num,
    })

    return results


def compare_services(old, new):
    results = []
    svc_old = old.get("services", {})
    svc_new = new.get("services", {})

    all_services = sorted(set(list(svc_old.keys()) + list(svc_new.keys())))

    for svc in all_services:
        old_st = svc_old.get(svc, "N/A")
        new_st = svc_new.get(svc, "N/A")
        status = eval_service_status(old_st, new_st)

        results.append({
            "item": f"Service: {svc}",
            "previous": str(old_st),
            "current": str(new_st),
            "status": status,
            "type": "text",
        })

    return results


def compare_network(old, new):
    results = []
    net_old = old.get("network", {})
    net_new = new.get("network", {})

    old_ips = ", ".join(net_old.get("ip_addresses", [])) or "None"
    new_ips = ", ".join(net_new.get("ip_addresses", [])) or "None"
    ip_changed = old_ips != new_ips

    results.append({
        "item": "Configured IP Addresses",
        "previous": old_ips,
        "current": new_ips,
        "status": "CHANGED" if ip_changed else "NO_CHANGE",
        "type": "text",
    })

    old_routes = len(net_old.get("routes", []))
    new_routes = len(net_new.get("routes", []))
    route_changed = old_routes != new_routes

    results.append({
        "item": "Active Network Routes",
        "previous": f"{old_routes} routes active",
        "current": f"{new_routes} routes active",
        "status": "CHANGED" if route_changed else "NO_CHANGE",
        "type": "text",
    })

    return results


def compare_security(old, new):
    results = []
    sec_old = old.get("security", {})
    sec_new = new.get("security", {})

    old_sel = sec_old.get("selinux", "N/A")
    new_sel = sec_new.get("selinux", "N/A")
    sel_changed = old_sel != new_sel

    results.append({
        "item": "SELinux Status",
        "previous": str(old_sel),
        "current": str(new_sel),
        "status": "CHANGED" if sel_changed else "NO_CHANGE",
        "type": "text",
    })

    old_ntp = sec_old.get("ntp", "N/A")
    new_ntp = sec_new.get("ntp", "N/A")
    ntp_changed = old_ntp != new_ntp

    results.append({
        "item": "NTP Time Synchronization",
        "previous": str(old_ntp),
        "current": str(new_ntp),
        "status": "CHANGED" if ntp_changed else "NO_CHANGE",
        "type": "text",
    })

    return results


def generate_summary(categories):
    counts = {"PASS": 0, "WARNING": 0, "FAIL": 0, "NO_CHANGE": 0, "CHANGED": 0, "total": 0}

    for cat_results in categories.values():
        for item in cat_results:
            st = item.get("status", "NO_CHANGE")
            if st in ("PASS", "RUNNING", "HEALTHY"):
                counts["PASS"] += 1
            elif st in ("WARNING", "CHANGED", "RESTARTED", "NEW"):
                counts["WARNING"] += 1
            elif st in ("FAIL", "STOPPED", "REMOVED", "DANGER"):
                counts["FAIL"] += 1
            else:
                counts["NO_CHANGE"] += 1

            if st != "NO_CHANGE":
                counts["CHANGED"] += 1

            counts["total"] += 1

    if counts["FAIL"] > 0:
        counts["overall"] = "FAIL"
    elif counts["WARNING"] > 0:
        counts["overall"] = "WARNING"
    else:
        counts["overall"] = "PASS"

    return counts


# =============================================================================
# ROUTES
# =============================================================================

@compare_bp.route("/compare/<hostname>", methods=["GET", "POST"])
@compare_bp.route("/compare/<hostname>/run", methods=["GET", "POST"])
def compare_page(hostname):
    """Unified route handling comparison GET and POST. Never returns blank page."""
    host_dir = os.path.join(Config.WEB_ROOT, hostname)
    if not os.path.isdir(host_dir):
        logger.warning("Compare requested for non-existent host directory: %s", hostname)
        abort(404)

    reports = get_json_reports(hostname)

    raw_old = request.form.get("report_old") or request.args.get("report_old")
    raw_new = request.form.get("report_new") or request.args.get("report_new")

    report_old = resolve_json_filename(raw_old) if raw_old else None
    report_new = resolve_json_filename(raw_new) if raw_new else None

    # Auto-select latest (new) and 2nd latest (old) if not specified
    if len(reports) >= 2:
        if not report_new:
            report_new = reports[0]["filename"]
        if not report_old:
            report_old = reports[1]["filename"]

    categories = None
    summary = None
    error_msg = None

    # Detailed Backend Logging
    logger.info("============================================================")
    logger.info("COMPARE WORKFLOW EXECUTED FOR HOST: %s", hostname)
    logger.info("Selected Previous Report (Raw): %s | Resolved JSON: %s", raw_old, report_old)
    logger.info("Selected Current Report (Raw) : %s | Resolved JSON: %s", raw_new, report_new)
    logger.info("Total JSON Reports Available  : %d", len(reports))

    if len(reports) < 2:
        error_msg = "At least two JSON health reports are required to perform a Before vs After activity comparison."
        logger.warning("Comparison aborted: insufficient reports (%d < 2) for %s", len(reports), hostname)
    elif report_old and report_new:
        old_path = os.path.join(host_dir, report_old)
        new_path = os.path.join(host_dir, report_new)

        old_exists = os.path.isfile(old_path)
        new_exists = os.path.isfile(new_path)

        old_size = os.path.getsize(old_path) if old_exists else 0
        new_size = os.path.getsize(new_path) if new_exists else 0

        logger.info("Resolved Previous File Path: %s | Exists: %s | Size: %d bytes", old_path, old_exists, old_size)
        logger.info("Resolved Current File Path : %s | Exists: %s | Size: %d bytes", new_path, new_exists, new_size)

        old_data, old_err = load_json(old_path)
        new_data, new_err = load_json(new_path)

        logger.info("JSON Parse Status (Previous): %s", "SUCCESS" if old_data else f"FAILED ({old_err})")
        logger.info("JSON Parse Status (Current) : %s", "SUCCESS" if new_data else f"FAILED ({new_err})")
        logger.info("============================================================")

        if old_data and new_data:
            categories = {
                "System Information": compare_system(old_data, new_data),
                "Storage & Mount Points": compare_storage(old_data, new_data),
                "Memory & Swap Usage": compare_memory(old_data, new_data),
                "Key Services": compare_services(old_data, new_data),
                "Network & Routes": compare_network(old_data, new_data),
                "Security & NTP": compare_security(old_data, new_data),
            }
            summary = generate_summary(categories)
        else:
            err_details = []
            if old_err:
                err_details.append(f"Previous Report ({report_old}): {old_err}")
            if new_err:
                err_details.append(f"Current Report ({report_new}): {new_err}")
            
            error_msg = "Unable to parse one or both report files.\n" + "\n".join(err_details)

    return render_template(
        "compare.html",
        hostname=hostname,
        json_reports=reports,
        results=categories,
        summary=summary,
        report_old=report_old,
        report_new=report_new,
        error_msg=error_msg,
        user=session.get("user"),
        auth_enabled=Config.AUTH_ENABLED,
    )
