"""
Compare blueprint — Before vs After report comparison engine.
Compares JSON summary files generated by health_check.sh.
Covers: System, Storage, Memory, Services, Network, Security.
"""

import os
import json
import logging
from datetime import datetime

from flask import Blueprint, render_template, request, jsonify, abort, session

from app.config import Config

compare_bp = Blueprint("compare", __name__)
logger = logging.getLogger(__name__)


# =============================================================================
# JSON LOADING
# =============================================================================

def load_json(filepath):
    """Load and return a JSON summary file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.error("Failed to load JSON %s: %s", filepath, e)
        return None


def get_json_reports(hostname):
    """Get all JSON reports for a hostname sorted newest-first."""
    host_dir = os.path.join(Config.WEB_ROOT, hostname)
    if not os.path.isdir(host_dir):
        return []

    reports = []
    for f in sorted(os.listdir(host_dir), reverse=True):
        if f.startswith("HealthCheck_") and f.endswith(".json"):
            fpath = os.path.join(host_dir, f)
            mtime = os.path.getmtime(fpath)
            reports.append({
                "filename": f,
                "mtime": mtime,
                "mtime_str": datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S"),
            })

    return reports


# =============================================================================
# STATUS EVALUATION RULES
# =============================================================================

def eval_filesystem_status(usage_pct):
    """Filesystem: <80%=PASS, 80-89%=WARNING, >=90%=FAIL."""
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 80:
        return "PASS"
    elif pct < 90:
        return "WARNING"
    return "FAIL"


def eval_memory_status(usage_pct):
    """Memory: <80%=PASS, 80-89%=WARNING, >=90%=FAIL."""
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 80:
        return "PASS"
    elif pct < 90:
        return "WARNING"
    return "FAIL"


def eval_swap_status(usage_pct):
    """Swap: <20%=PASS, 20-49%=WARNING, >=50%=FAIL."""
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 20:
        return "PASS"
    elif pct < 50:
        return "WARNING"
    return "FAIL"


def eval_service_status(state):
    """Service: Running=PASS, Stopped=FAIL."""
    if not state:
        return "INFO"
    s = str(state).upper()
    if s in ("RUNNING", "ACTIVE"):
        return "PASS"
    elif s in ("NOT_INSTALLED",):
        return "INFO"
    return "FAIL"


def eval_selinux_status(state):
    """SELinux: Enforcing=PASS, Permissive=WARNING, Disabled=FAIL."""
    if not state:
        return "INFO"
    s = str(state).lower()
    if "enforcing" in s:
        return "PASS"
    elif "permissive" in s:
        return "WARNING"
    return "FAIL"


def eval_ntp_status(state):
    """NTP: Synchronized=PASS, Not synchronized=FAIL."""
    if not state:
        return "INFO"
    s = str(state).lower()
    if "synchronized" in s and "not" not in s:
        return "PASS"
    return "FAIL"


def eval_change_status(old_val, new_val, category="generic"):
    """Evaluate whether a value change is PASS, INFO, or WARNING."""
    if str(old_val) == str(new_val):
        return "PASS"
    if category in ("kernel", "os", "cpu", "ram", "ip"):
        return "INFO"
    if category == "routes":
        return "WARNING"
    return "INFO"


# =============================================================================
# COMPARISON FUNCTIONS
# =============================================================================

def compare_system(old, new):
    """Compare system-level fields."""
    results = []
    sys_old = old.get("system", {})
    sys_new = new.get("system", {})

    fields = [
        ("Hostname", "hostname", "generic"),
        ("FQDN", "fqdn", "generic"),
        ("Operating System", "os", "os"),
        ("Kernel", "kernel", "kernel"),
        ("CPU Cores", "cpu_cores", "cpu"),
        ("RAM Total", "ram_total", "ram"),
        ("Uptime", "uptime", "generic"),
    ]

    for label, key, category in fields:
        old_val = sys_old.get(key, "N/A")
        new_val = sys_new.get(key, "N/A")
        diff = "No Change" if str(old_val) == str(new_val) else "Changed"
        status = eval_change_status(old_val, new_val, category)
        results.append({
            "item": label,
            "previous": str(old_val),
            "current": str(new_val),
            "difference": diff,
            "status": status,
        })

    return results


def compare_storage(old, new):
    """Compare filesystem usage and mount points."""
    results = []

    fs_old = {item["mount"]: item for item in old.get("storage", {}).get("filesystems", [])}
    fs_new = {item["mount"]: item for item in new.get("storage", {}).get("filesystems", [])}

    all_mounts = sorted(set(list(fs_old.keys()) + list(fs_new.keys())))

    for mount in all_mounts:
        old_entry = fs_old.get(mount, {})
        new_entry = fs_new.get(mount, {})

        old_use = old_entry.get("use_pct", "N/A")
        new_use = new_entry.get("use_pct", "N/A")

        if mount not in fs_old:
            diff = "NEW mount point"
            status = "INFO"
        elif mount not in fs_new:
            diff = "MISSING mount point"
            status = "FAIL"
        elif str(old_use) == str(new_use):
            diff = "No Change"
            status = eval_filesystem_status(new_use)
        else:
            diff = f"{old_use} → {new_use}"
            status = eval_filesystem_status(new_use)

        old_detail = f"{old_entry.get('filesystem', 'N/A')} {old_entry.get('size', '')} Used:{old_use}" if old_entry else "N/A"
        new_detail = f"{new_entry.get('filesystem', 'N/A')} {new_entry.get('size', '')} Used:{new_use}" if new_entry else "N/A"

        results.append({
            "item": f"Mount: {mount}",
            "previous": old_detail,
            "current": new_detail,
            "difference": diff,
            "status": status,
        })

    return results


def compare_memory(old, new):
    """Compare RAM and swap usage."""
    results = []

    mem_old = old.get("memory", {})
    mem_new = new.get("memory", {})

    # RAM
    old_ram = mem_old.get("ram_used_pct", "N/A")
    new_ram = mem_new.get("ram_used_pct", "N/A")
    diff = "No Change" if str(old_ram) == str(new_ram) else f"{old_ram} → {new_ram}"
    results.append({
        "item": "RAM Usage",
        "previous": f"{mem_old.get('ram_used', 'N/A')} / {mem_old.get('ram_total', 'N/A')} ({old_ram})",
        "current": f"{mem_new.get('ram_used', 'N/A')} / {mem_new.get('ram_total', 'N/A')} ({new_ram})",
        "difference": diff,
        "status": eval_memory_status(new_ram),
    })

    # Swap
    old_swap = mem_old.get("swap_used_pct", "N/A")
    new_swap = mem_new.get("swap_used_pct", "N/A")
    diff = "No Change" if str(old_swap) == str(new_swap) else f"{old_swap} → {new_swap}"
    results.append({
        "item": "Swap Usage",
        "previous": f"{mem_old.get('swap_used', 'N/A')} / {mem_old.get('swap_total', 'N/A')} ({old_swap})",
        "current": f"{mem_new.get('swap_used', 'N/A')} / {mem_new.get('swap_total', 'N/A')} ({new_swap})",
        "difference": diff,
        "status": eval_swap_status(new_swap),
    })

    return results


def compare_services(old, new):
    """Compare key service states."""
    results = []

    svc_old = old.get("services", {})
    svc_new = new.get("services", {})

    all_services = sorted(set(list(svc_old.keys()) + list(svc_new.keys())))

    for svc in all_services:
        old_state = svc_old.get(svc, "N/A")
        new_state = svc_new.get(svc, "N/A")
        diff = "No Change" if str(old_state) == str(new_state) else f"{old_state} → {new_state}"
        results.append({
            "item": svc,
            "previous": str(old_state),
            "current": str(new_state),
            "difference": diff,
            "status": eval_service_status(new_state),
        })

    return results


def compare_network(old, new):
    """Compare IP addresses and routes."""
    results = []

    net_old = old.get("network", {})
    net_new = new.get("network", {})

    # IP Addresses
    old_ips = net_old.get("ip_addresses", [])
    new_ips = net_new.get("ip_addresses", [])
    old_ips_str = "\n".join(old_ips) if isinstance(old_ips, list) else str(old_ips)
    new_ips_str = "\n".join(new_ips) if isinstance(new_ips, list) else str(new_ips)
    diff = "No Change" if old_ips_str == new_ips_str else "Changed"
    results.append({
        "item": "IP Addresses",
        "previous": old_ips_str or "N/A",
        "current": new_ips_str or "N/A",
        "difference": diff,
        "status": eval_change_status(old_ips_str, new_ips_str, "ip"),
    })

    # Routes
    old_routes = net_old.get("routes", [])
    new_routes = net_new.get("routes", [])
    old_routes_str = "\n".join(old_routes) if isinstance(old_routes, list) else str(old_routes)
    new_routes_str = "\n".join(new_routes) if isinstance(new_routes, list) else str(new_routes)
    diff = "No Change" if old_routes_str == new_routes_str else "Changed"

    # Check for missing persist routes
    if old_routes_str != new_routes_str:
        old_set = set(old_routes) if isinstance(old_routes, list) else set()
        new_set = set(new_routes) if isinstance(new_routes, list) else set()
        missing = old_set - new_set
        added = new_set - old_set
        details = []
        if missing:
            details.append(f"Removed: {', '.join(missing)}")
        if added:
            details.append(f"Added: {', '.join(added)}")
        diff = "; ".join(details) if details else "Changed"

    results.append({
        "item": "Routes (route -n / ip route)",
        "previous": old_routes_str or "N/A",
        "current": new_routes_str or "N/A",
        "difference": diff,
        "status": eval_change_status(old_routes_str, new_routes_str, "routes"),
    })

    return results


def compare_security(old, new):
    """Compare SELinux and NTP status."""
    results = []

    sec_old = old.get("security", {})
    sec_new = new.get("security", {})

    # SELinux
    old_se = sec_old.get("selinux", "N/A")
    new_se = sec_new.get("selinux", "N/A")
    diff = "No Change" if str(old_se) == str(new_se) else f"{old_se} → {new_se}"
    results.append({
        "item": "SELinux",
        "previous": str(old_se),
        "current": str(new_se),
        "difference": diff,
        "status": eval_selinux_status(new_se),
    })

    # NTP
    old_ntp = sec_old.get("ntp", "N/A")
    new_ntp = sec_new.get("ntp", "N/A")
    diff = "No Change" if str(old_ntp) == str(new_ntp) else f"{old_ntp} → {new_ntp}"
    results.append({
        "item": "NTP Synchronization",
        "previous": str(old_ntp),
        "current": str(new_ntp),
        "difference": diff,
        "status": eval_ntp_status(new_ntp),
    })

    return results


def generate_summary(categories):
    """Count PASS/WARNING/FAIL/INFO across all categories."""
    counts = {"PASS": 0, "WARNING": 0, "FAIL": 0, "INFO": 0, "total": 0}

    for cat_results in categories.values():
        for item in cat_results:
            status = item.get("status", "INFO")
            counts[status] = counts.get(status, 0) + 1
            counts["total"] += 1

    # Overall health
    if counts["FAIL"] > 0:
        counts["overall"] = "FAIL"
    elif counts["WARNING"] > 0:
        counts["overall"] = "WARNING"
    else:
        counts["overall"] = "PASS"

    # Changes detected
    counts["changes"] = sum(
        1 for cat_results in categories.values()
        for item in cat_results
        if item.get("difference", "") != "No Change"
    )

    return counts


# =============================================================================
# ROUTES
# =============================================================================

@compare_bp.route("/compare/<hostname>")
def compare_page(hostname):
    """Show the comparison page with report selectors."""
    reports = get_json_reports(hostname)

    return render_template(
        "compare.html",
        hostname=hostname,
        json_reports=reports,
        results=None,
        summary=None,
        user=session.get("user"),
        auth_enabled=Config.AUTH_ENABLED,
    )


@compare_bp.route("/compare/<hostname>/run", methods=["POST"])
def run_comparison(hostname):
    """Execute comparison between two selected JSON reports."""
    report_old = request.form.get("report_old", "")
    report_new = request.form.get("report_new", "")

    host_dir = os.path.join(Config.WEB_ROOT, hostname)
    old_path = os.path.join(host_dir, report_old)
    new_path = os.path.join(host_dir, report_new)

    if not os.path.isfile(old_path) or not os.path.isfile(new_path):
        abort(400)

    old_data = load_json(old_path)
    new_data = load_json(new_path)

    if old_data is None or new_data is None:
        abort(500)

    # Run all comparisons
    categories = {
        "System": compare_system(old_data, new_data),
        "Storage": compare_storage(old_data, new_data),
        "Memory": compare_memory(old_data, new_data),
        "Services": compare_services(old_data, new_data),
        "Network": compare_network(old_data, new_data),
        "Security": compare_security(old_data, new_data),
    }

    summary = generate_summary(categories)

    reports = get_json_reports(hostname)

    return render_template(
        "compare.html",
        hostname=hostname,
        json_reports=reports,
        results=categories,
        summary=summary,
        report_old=report_old,
        report_new=report_new,
        user=session.get("user"),
        auth_enabled=Config.AUTH_ENABLED,
    )


@compare_bp.route("/api/json-reports/<hostname>")
def api_json_reports(hostname):
    """API endpoint returning available JSON reports for a host."""
    reports = get_json_reports(hostname)
    return jsonify({"hostname": hostname, "reports": reports})
