"""
Compare blueprint — Before vs After report comparison engine.
Compares JSON summary files generated by health_check.sh.
Covers: System, Storage, Memory, Services, Network, Security.
"""

import os
import json
import logging
from datetime import datetime

from flask import Blueprint, render_template, request, jsonify, abort, session, redirect, url_for

from app.config import Config

compare_bp = Blueprint("compare", __name__)
logger = logging.getLogger(__name__)


# =============================================================================
# JSON LOADING & REPORT DISCOVERY
# =============================================================================

def load_json(filepath):
    """Load and return a JSON summary file."""
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.error("Failed to load JSON %s: %s", filepath, e)
        return None


def get_json_reports(hostname):
    """Get all JSON reports for a hostname sorted newest-first."""
    host_dir = os.path.join(Config.WEB_ROOT, hostname)
    if not os.path.isdir(host_dir):
        return []

    reports = []
    for f in sorted(os.listdir(host_dir), reverse=True):
        if f.startswith("HealthCheck_") and f.endswith(".json"):
            fpath = os.path.join(host_dir, f)
            mtime = os.path.getmtime(fpath)
            reports.append({
                "filename": f,
                "mtime": mtime,
                "mtime_str": datetime.fromtimestamp(mtime).strftime("%Y-%m-%d %H:%M:%S"),
            })

    return reports


# =============================================================================
# COMPARISON ENGINE
# =============================================================================

def eval_filesystem_status(usage_pct):
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 80:
        return "PASS"
    elif pct < 90:
        return "WARNING"
    return "FAIL"


def eval_memory_status(usage_pct):
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 80:
        return "PASS"
    elif pct < 90:
        return "WARNING"
    return "FAIL"


def eval_swap_status(usage_pct):
    try:
        pct = float(str(usage_pct).replace("%", ""))
    except (ValueError, TypeError):
        return "INFO"
    if pct < 20:
        return "PASS"
    elif pct < 50:
        return "WARNING"
    return "FAIL"


def eval_service_status(old_state, new_state):
    s_new = str(new_state).upper() if new_state else "UNKNOWN"
    s_old = str(old_state).upper() if old_state else "UNKNOWN"

    if s_old == "STOPPED" and s_new in ("RUNNING", "ACTIVE"):
        return "RESTARTED"
    elif s_new in ("RUNNING", "ACTIVE"):
        return "RUNNING"
    elif s_new == "STOPPED":
        return "STOPPED"
    elif s_new == "NOT_INSTALLED":
        return "REMOVED"
    return "CHANGED" if s_old != s_new else "NO_CHANGE"


def compare_system(old, new):
    results = []
    sys_old = old.get("system", {})
    sys_new = new.get("system", {})

    fields = [
        ("Hostname", "hostname"),
        ("FQDN", "fqdn"),
        ("Operating System", "os"),
        ("Kernel Version", "kernel"),
        ("CPU Cores", "cpu_cores"),
        ("Total Memory", "ram_total"),
        ("System Uptime", "uptime"),
    ]

    for label, key in fields:
        old_val = str(sys_old.get(key, "N/A"))
        new_val = str(sys_new.get(key, "N/A"))
        changed = old_val != new_val
        results.append({
            "item": label,
            "previous": old_val,
            "current": new_val,
            "difference": f"{old_val} → {new_val}" if changed else "No Change",
            "status": "CHANGED" if changed else "NO_CHANGE",
            "type": "text",
        })

    return results


def compare_storage(old, new):
    results = []

    fs_old = {item["mount"]: item for item in old.get("storage", {}).get("filesystems", [])}
    fs_new = {item["mount"]: item for item in new.get("storage", {}).get("filesystems", [])}

    all_mounts = sorted(set(list(fs_old.keys()) + list(fs_new.keys())))

    for mount in all_mounts:
        old_entry = fs_old.get(mount, {})
        new_entry = fs_new.get(mount, {})

        old_use = old_entry.get("use_pct", "0%")
        new_use = new_entry.get("use_pct", "0%")

        try:
            old_num = float(str(old_use).replace("%", ""))
        except Exception:
            old_num = 0

        try:
            new_num = float(str(new_use).replace("%", ""))
        except Exception:
            new_num = 0

        if mount not in fs_old:
            status = "NEW"
            diff = "New mount point added"
        elif mount not in fs_new:
            status = "REMOVED"
            diff = "Mount point removed"
        elif old_use != new_use:
            status = eval_filesystem_status(new_use)
            diff = f"{old_use} → {new_use}"
        else:
            status = "NO_CHANGE"
            diff = "No Change"

        results.append({
            "item": f"Mount: {mount}",
            "previous": f"{old_entry.get('size', 'N/A')} (Used: {old_use})",
            "current": f"{new_entry.get('size', 'N/A')} (Used: {new_use})",
            "prev_pct": old_num,
            "curr_pct": new_num,
            "difference": diff,
            "status": status,
            "type": "progress",
        })

    return results


def compare_memory(old, new):
    results = []

    mem_old = old.get("memory", {})
    mem_new = new.get("memory", {})

    # RAM
    old_ram_pct = mem_old.get("ram_used_pct", "0%")
    new_ram_pct = mem_new.get("ram_used_pct", "0%")
    try:
        ram_prev_num = float(str(old_ram_pct).replace("%", ""))
        ram_curr_num = float(str(new_ram_pct).replace("%", ""))
    except Exception:
        ram_prev_num = ram_curr_num = 0

    ram_changed = old_ram_pct != new_ram_pct
    results.append({
        "item": "RAM Usage",
        "previous": f"{mem_old.get('ram_used', 'N/A')} / {mem_old.get('ram_total', 'N/A')} ({old_ram_pct})",
        "current": f"{mem_new.get('ram_used', 'N/A')} / {mem_new.get('ram_total', 'N/A')} ({new_ram_pct})",
        "prev_pct": ram_prev_num,
        "curr_pct": ram_curr_num,
        "difference": f"{old_ram_pct} → {new_ram_pct}" if ram_changed else "No Change",
        "status": eval_memory_status(new_ram_pct),
        "type": "progress",
    })

    # Swap
    old_swap_pct = mem_old.get("swap_used_pct", "0%")
    new_swap_pct = mem_new.get("swap_used_pct", "0%")
    try:
        swap_prev_num = float(str(old_swap_pct).replace("%", ""))
        swap_curr_num = float(str(new_swap_pct).replace("%", ""))
    except Exception:
        swap_prev_num = swap_curr_num = 0

    swap_changed = old_swap_pct != new_swap_pct
    results.append({
        "item": "Swap Usage",
        "previous": f"{mem_old.get('swap_used', 'N/A')} / {mem_old.get('swap_total', 'N/A')} ({old_swap_pct})",
        "current": f"{mem_new.get('swap_used', 'N/A')} / {mem_new.get('swap_total', 'N/A')} ({new_swap_pct})",
        "prev_pct": swap_prev_num,
        "curr_pct": swap_curr_num,
        "difference": f"{old_swap_pct} → {new_swap_pct}" if swap_changed else "No Change",
        "status": eval_swap_status(new_swap_pct),
        "type": "progress",
    })

    return results


def compare_services(old, new):
    results = []

    svc_old = old.get("services", {})
    svc_new = new.get("services", {})

    all_services = sorted(set(list(svc_old.keys()) + list(svc_new.keys())))

    for svc in all_services:
        old_state = svc_old.get(svc, "N/A")
        new_state = svc_new.get(svc, "N/A")
        changed = str(old_state) != str(new_state)
        status = eval_service_status(old_state, new_state)

        results.append({
            "item": f"Service: {svc}",
            "previous": str(old_state),
            "current": str(new_state),
            "difference": f"{old_state} → {new_state}" if changed else "No Change",
            "status": status,
            "type": "service",
        })

    return results


def compare_network(old, new):
    results = []

    net_old = old.get("network", {})
    net_new = new.get("network", {})

    # IP Addresses
    old_ips = net_old.get("ip_addresses", [])
    new_ips = net_new.get("ip_addresses", [])
    old_ips_str = ", ".join(old_ips) if isinstance(old_ips, list) else str(old_ips)
    new_ips_str = ", ".join(new_ips) if isinstance(new_ips, list) else str(new_ips)
    ip_changed = old_ips_str != new_ips_str
    results.append({
        "item": "IP Addresses",
        "previous": old_ips_str or "N/A",
        "current": new_ips_str or "N/A",
        "difference": "Changed" if ip_changed else "No Change",
        "status": "CHANGED" if ip_changed else "NO_CHANGE",
        "type": "text",
    })

    # Routes
    old_routes = net_old.get("routes", [])
    new_routes = net_new.get("routes", [])
    old_routes_str = "\n".join(old_routes) if isinstance(old_routes, list) else str(old_routes)
    new_routes_str = "\n".join(new_routes) if isinstance(new_routes, list) else str(new_routes)
    route_changed = old_routes_str != new_routes_str

    diff_desc = "No Change"
    if route_changed:
        old_set = set(old_routes) if isinstance(old_routes, list) else set()
        new_set = set(new_routes) if isinstance(new_routes, list) else set()
        removed = old_set - new_set
        added = new_set - old_set
        desc_parts = []
        if removed:
            desc_parts.append(f"Removed routes: {', '.join(removed)}")
        if added:
            desc_parts.append(f"Added routes: {', '.join(added)}")
        diff_desc = "; ".join(desc_parts) if desc_parts else "Routing table changed"

    results.append({
        "item": "Network Routes (route -n)",
        "previous": old_routes_str or "N/A",
        "current": new_routes_str or "N/A",
        "difference": diff_desc,
        "status": "WARNING" if route_changed else "NO_CHANGE",
        "type": "text",
    })

    return results


def compare_security(old, new):
    results = []

    sec_old = old.get("security", {})
    sec_new = new.get("security", {})

    # SELinux
    old_se = sec_old.get("selinux", "N/A")
    new_se = sec_new.get("selinux", "N/A")
    se_changed = str(old_se) != str(new_se)
    results.append({
        "item": "SELinux Mode",
        "previous": str(old_se),
        "current": str(new_se),
        "difference": f"{old_se} → {new_se}" if se_changed else "No Change",
        "status": "CHANGED" if se_changed else "NO_CHANGE",
        "type": "text",
    })

    # NTP
    old_ntp = sec_old.get("ntp", "N/A")
    new_ntp = sec_new.get("ntp", "N/A")
    ntp_changed = str(old_ntp) != str(new_ntp)
    results.append({
        "item": "NTP Synchronization",
        "previous": str(old_ntp),
        "current": str(new_ntp),
        "difference": f"{old_ntp} → {new_ntp}" if ntp_changed else "No Change",
        "status": "CHANGED" if ntp_changed else "NO_CHANGE",
        "type": "text",
    })

    return results


def generate_summary(categories):
    counts = {"PASS": 0, "WARNING": 0, "FAIL": 0, "NO_CHANGE": 0, "CHANGED": 0, "total": 0}

    for cat_results in categories.values():
        for item in cat_results:
            st = item.get("status", "NO_CHANGE")
            if st in ("PASS", "RUNNING", "HEALTHY"):
                counts["PASS"] += 1
            elif st in ("WARNING", "CHANGED", "RESTARTED", "NEW"):
                counts["WARNING"] += 1
            elif st in ("FAIL", "STOPPED", "REMOVED", "DANGER"):
                counts["FAIL"] += 1
            else:
                counts["NO_CHANGE"] += 1

            if st != "NO_CHANGE":
                counts["CHANGED"] += 1

            counts["total"] += 1

    if counts["FAIL"] > 0:
        counts["overall"] = "FAIL"
    elif counts["WARNING"] > 0:
        counts["overall"] = "WARNING"
    else:
        counts["overall"] = "PASS"

    return counts


# =============================================================================
# ROUTES
# =============================================================================

@compare_bp.route("/compare/<hostname>", methods=["GET", "POST"])
@compare_bp.route("/compare/<hostname>/run", methods=["GET", "POST"])
def compare_page(hostname):
    """Unified route handling comparison GET and POST. Never returns blank page."""
    reports = get_json_reports(hostname)

    report_old = request.form.get("report_old") or request.args.get("report_old")
    report_new = request.form.get("report_new") or request.args.get("report_new")

    # Default to latest and 2nd latest if not selected
    if len(reports) >= 2:
        if not report_new:
            report_new = reports[0]["filename"]
        if not report_old:
            report_old = reports[1]["filename"]

    categories = None
    summary = None
    error_msg = None

    if len(reports) < 2:
        error_msg = "At least two JSON health reports are required to perform a Before vs After activity comparison."
    elif report_old and report_new:
        host_dir = os.path.join(Config.WEB_ROOT, hostname)
        old_path = os.path.join(host_dir, report_old)
        new_path = os.path.join(host_dir, report_new)

        if os.path.isfile(old_path) and os.path.isfile(new_path):
            old_data = load_json(old_path)
            new_data = load_json(new_path)

            if old_data and new_data:
                categories = {
                    "System Information": compare_system(old_data, new_data),
                    "Storage & Mount Points": compare_storage(old_data, new_data),
                    "Memory & Swap Usage": compare_memory(old_data, new_data),
                    "Key Services": compare_services(old_data, new_data),
                    "Network & Routes": compare_network(old_data, new_data),
                    "Security & NTP": compare_security(old_data, new_data),
                }
                summary = generate_summary(categories)
            else:
                error_msg = "Failed to parse one or both JSON report files."
        else:
            error_msg = "Selected report files do not exist."

    return render_template(
        "compare.html",
        hostname=hostname,
        json_reports=reports,
        results=categories,
        summary=summary,
        report_old=report_old,
        report_new=report_new,
        error_msg=error_msg,
        user=session.get("user"),
        auth_enabled=Config.AUTH_ENABLED,
    )
